/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.junit.Before;
import org.junit.Test;

import static org.junit.Assert.assertEquals;

public class LibraryTest {
    private Injector injector;

    @Before
    public void setup() {
        injector = Guice.createInjector(new RodriModule());
    }

    @Test
    public void testMLA() {
        PresenterBySite p = injector.getInstance(PresenterBySite.class);


        assertEquals("mla presenter", p.presentFor("MLA"));
    }

    @Test
    public void testMLB() {
        PresenterBySite p = injector.getInstance(PresenterBySite.class);


        assertEquals("mlb presenter", p.presentFor("MLB"));
    }
}
